language: python

python:
- '3.4'
- '3.5'
- '3.6'
- '3.7'

install:
- pip install -e .
- pip install -r requirements.txt

script: 
- travis_retry python -m pytest
- flake8 masonite/ --ignore=E501,F401,E128,E402,E731,F821,E712,W503
