version: 2
jobs:
  Builds:
    build:
      steps:
        - checkout
        - run: echo "A first hello"
    build:
      steps:
        - checkout
        - run: echo "A first hello"    

workflows:
  version: 2
  Builds:
    jobs:
      - Builds