version: 2
jobs:
  build:
    steps:
      - checkout
      - run: echo "hi"
  test:
    steps:
      - checkout
      - run: echo "yo"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test