version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.4  # primary container for the build job
    steps:
      - checkout
      - run: 
        - pip install -e .
        - pip install -r requirements.txt
        - python -m pytest

workflows:
  version: 2
  build_and_test:
    jobs:
      - build