version: 2
jobs:
  build:
      python3.4:
        docker:
          - image: circleci/python:3.4  # primary container for the build job
        steps:
          - checkout
          - run: pip install -e . --user
          - run: pip install -r requirements.txt --user
          - run: python -m pytest
      python3.5:
        docker:
          - image: circleci/python:3.5  # primary container for the build job
        steps:
          - checkout
          - run: pip install -e . --user
          - run: pip install -r requirements.txt --user
          - run: python -m pytest
      python3.6:
        docker:
          - image: circleci/python:3.6  # primary container for the build job
        steps:
          - checkout
          - run: pip install -e . --user
          - run: pip install -r requirements.txt --user
          - run: python -m pytest
      python3.7:
        docker:
          - image: circleci/python:3.7  # primary container for the build job
        steps:
          - checkout
          - run: pip install -e . --user
          - run: pip install -r requirements.txt --user
          - run: python -m pytest


workflows:
  version: 2
  build_and_test:
    jobs: 
      - python3.4
      - python3.5
      - python3.6
      - python3.7
      - trigger_core:
          requires:
              - python3.4
              - python3.5
              - python3.6
              - python3.7